[workspace]
members = [
    'imxrt1062-rt',
    'teensy4-bsp',
    'teensy4-bsp/teensy4-usb-sys',
    'teensy4-examples',
    'teensy4-fcb',
]
exclude = [
    'tools',
    'imxrt1062-fcb-gen',
    'svd/imxrt1062',
]
