[workspace]
members = [
    'imxrt1062-hal',
    'imxrt1062-pac',
    'imxrt1062-pac/imxrt1062-adc-etc',
    'imxrt1062-pac/imxrt1062-adc1',
    'imxrt1062-pac/imxrt1062-aipstz1',
    'imxrt1062-pac/imxrt1062-aoi1',
    'imxrt1062-pac/imxrt1062-bee',
    'imxrt1062-pac/imxrt1062-can1',
    'imxrt1062-pac/imxrt1062-can3',
    'imxrt1062-pac/imxrt1062-ccm',
    'imxrt1062-pac/imxrt1062-ccm-analog',
    'imxrt1062-pac/imxrt1062-cmp1',
    'imxrt1062-pac/imxrt1062-core',
    'imxrt1062-pac/imxrt1062-csi',
    'imxrt1062-pac/imxrt1062-csu',
    'imxrt1062-pac/imxrt1062-dcdc',
    'imxrt1062-pac/imxrt1062-dcp',
    'imxrt1062-pac/imxrt1062-dma0',
    'imxrt1062-pac/imxrt1062-dmamux',
    'imxrt1062-pac/imxrt1062-enc1',
    'imxrt1062-pac/imxrt1062-enet',
    'imxrt1062-pac/imxrt1062-ewm',
    'imxrt1062-pac/imxrt1062-flexio1',
    'imxrt1062-pac/imxrt1062-flexram',
    'imxrt1062-pac/imxrt1062-flexspi',
    'imxrt1062-pac/imxrt1062-gpc',
    'imxrt1062-pac/imxrt1062-gpio1',
    'imxrt1062-pac/imxrt1062-gpt1',
    'imxrt1062-pac/imxrt1062-iomuxc',
    'imxrt1062-pac/imxrt1062-iomuxc-gpr',
    'imxrt1062-pac/imxrt1062-iomuxc-snvs',
    'imxrt1062-pac/imxrt1062-iomuxc-snvs-gpr',
    'imxrt1062-pac/imxrt1062-kpp',
    'imxrt1062-pac/imxrt1062-lcdif',
    'imxrt1062-pac/imxrt1062-lpi2c1',
    'imxrt1062-pac/imxrt1062-lpspi1',
    'imxrt1062-pac/imxrt1062-lpuart1',
    'imxrt1062-pac/imxrt1062-ocotp',
    'imxrt1062-pac/imxrt1062-pgc',
    'imxrt1062-pac/imxrt1062-pit',
    'imxrt1062-pac/imxrt1062-pmu',
    'imxrt1062-pac/imxrt1062-pwm1',
    'imxrt1062-pac/imxrt1062-pxp',
    'imxrt1062-pac/imxrt1062-romc',
    'imxrt1062-pac/imxrt1062-rtwdog',
    'imxrt1062-pac/imxrt1062-sai1',
    'imxrt1062-pac/imxrt1062-semc',
    'imxrt1062-pac/imxrt1062-snvs',
    'imxrt1062-pac/imxrt1062-spdif',
    'imxrt1062-pac/imxrt1062-src',
    'imxrt1062-pac/imxrt1062-system-control',
    'imxrt1062-pac/imxrt1062-tempmon',
    'imxrt1062-pac/imxrt1062-tmr1',
    'imxrt1062-pac/imxrt1062-trng',
    'imxrt1062-pac/imxrt1062-tsc',
    'imxrt1062-pac/imxrt1062-usb-analog',
    'imxrt1062-pac/imxrt1062-usb1',
    'imxrt1062-pac/imxrt1062-usbnc1',
    'imxrt1062-pac/imxrt1062-usbphy1',
    'imxrt1062-pac/imxrt1062-usdhc1',
    'imxrt1062-pac/imxrt1062-wdog1',
    'imxrt1062-pac/imxrt1062-xbara1',
    'imxrt1062-pac/imxrt1062-xbarb2',
    'imxrt1062-pac/imxrt1062-xtalosc24m',
    'imxrt1062-rt',
    'teensy4-bsp',
    'teensy4-bsp/teensy4-usb-sys',
    'teensy4-examples',
    'teensy4-fcb',
]
exclude = [
    'tools',
    'svd/imxrt1062',
]
