[package]
name = 'imxrt1062-dma0'
version = '0.2.0'
categories = [
    'embedded',
    'hardware-support',
    'no-std',
]
keywords = [
    'arm',
    'svd2rust',
    'imxrt1062',
    'cortex-m',
]
description = '''
An imxrt1062-pac subcrate. See the imxrt1062-pac for more details.

Part of the teensy4-rs project.        
'''
license = 'MIT OR Apache-2.0'
repository = 'https://github.com/mciantyre/teensy4-rs'
authors = ['Ian McIntyre <ianpmcintyre@gmail.com>']
edition = '2018'

[dependencies]
vcell = '0.1.2'

[lib]
bench = false
test = false
